### ISSUE TITLE
New Line not working

### ISSUE THREAD

**Issue by nonpostrans** [bjarnekvae/pymobitec-flipdot#2]
Hello!

Great work, it works like charm on my Flip Dot Display.
However I have some questions:

a) What is the best way to use two lines of small  text? Newline character doesnt work.
b) What is the best way to turn all pixels to 1 ? I need to check for dead pixels.
b) How to use "symbols = 0x67" font and what is " bitwise" font?

Thanks in advance!!

**Comment by nonpostrans** [comment]
I also found an issue: Some functions like clear_display() and _set_pixels() expect an [28, 20] array. This is okay for an 28x20 Display. But mine is larger and I need to change these numbers to my size accordingly. It would be better to take the  # Display width as a variable and change these fix number 28 accordingly. (If I got the code right)
The code as it is changes only the first 28 pixels in my display. After changing it to the actual width it is changing all pixels.

**Comment by bjarnekvae** [comment]
Hi,

a) New line is not supported in the current state of the code, however, it should not be hard to implement, e.g. look at the function "set_text_and_pixels", you could call "_set_text" twice here one for each line (insted of "_set_pixels").
b) You could feed all pixel coordinates into the "set_pixels" function, or you could make a new function based on "clear_display" where "pix_map = np.zeros([28, 20], dtype=np.bool)" on line 170 is changed to "pix_map = np.ones([28, 20], dtype=np.bool)".
c) If I remember correctly the symbols font are small icons of buildings and stuff, you use it with the "set_text" function where the text is a hex value. I never categorized the exact hex value for each icon, you just need to do some trial an error here.
The bitwise font is how you can set individual pixels on the display, each "font" is a vertical 5-bit binary sequence where e.g 0x00 = 00000, 0x01 = 00001, 0x02 = 00010, etc... I have used this in the "set_pixels" and "clear_display" functions.

The current state of the code is not optimal - all functions should be in its own class so that the display size could be initialized in the constructor. Its on the todo-list, but haven't been prioritized as this repo doesn't see much traffic anyway, and its a quick fix to alter to other display sizes.
